### ISSUE TITLE
ace editor value watch function

### ISSUE THREAD

**Issue by RussNZ** [Hector101/vue2-brace-editor#2]
Great project, but i've found a small bug in your value watch function, nextProps is undefined.

Should this be pos.cursorStart?

```
'value': function(newVal, oldVal) {
        if (this.editor && this.editor.getValue() !== newVal) {
          // editor.setValue is a synchronous function call, change event is emitted before setValue return.
          this.silent = true;
          const pos = this.editor.session.selection.toJSON();
          this.editor.setValue(newVal, nextProps.cursorStart);
          this.editor.session.selection.fromJSON(pos);
          this.silent = false;
        }
 },
```

**Comment by Hector101** [comment]
I'll try to address the issue, thanks.

**Comment by jkosonen** [comment]
@Hector101 still an issue..

**Comment by Hector101** [comment]
@jkosonen I've merged your PR. Thanks for raising this issue.

**Comment by mbana** [comment]
Did you release a version with the fix?

If not how are you folks managing to use this library?

I am getting the same error and i think this happens when you modify the bound value within a `method`.

**Comment by Hector101** [comment]
@mbana I had fixed the error on my project, but have been quite tied up to update on npm.
You can check it out, I've published the fix.

The recent version is version 2.0.2.

Sorry for the inconvenience I may have cause you. I'm opened to more suggestions
